name = "gta-ai-clone"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.kv_namespaces]]
binding = "CACHE"
id = ""

[build]
command = "npm run build"