// Cloudflare Functions API route for image transformation
import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize Gemini client - will be set per request
let genAI;

async function generateGTAStyleImage(imageFile) {
  try {
    // Convert file to base64
    const arrayBuffer = await imageFile.arrayBuffer();
    const base64String = btoa(String.fromCharCode.apply(null, new Uint8Array(arrayBuffer)));
    
    // Create image part for Gemini
    const imagePart = {
      inlineData: {
        data: base64String,
        mimeType: imageFile.type,
      },
    };

    // Enhanced GTA-style transformation prompt
    const gtaPrompt = `Transform this image into GTA (Grand Theft Auto) style art. Create a stylized, comic book-like version with:
- Bold outlines and cell-shaded coloring
- Vibrant, saturated colors typical of GTA artwork
- Slightly exaggerated features and proportions
- Urban, street art aesthetic
- High contrast lighting
- Maintain the original subject but give it that distinctive GTA visual style
- Make it look like official GTA character art or promotional material

Generate a new image in this style, not just describe it.`;

    // Use Gemini 2.0 Flash for image generation
    const imageGenModel = genAI.getGenerativeModel({ model: 'gemini-2.0-flash-exp' });
    const imageGenResult = await imageGenModel.generateContent(gtaPrompt);
    
    const generatedParts = imageGenResult.response.candidates[0]?.content?.parts || [];
    const generatedImagePart = generatedParts.find((part) => part.inlineData?.data);
    
    if (generatedImagePart && generatedImagePart.inlineData?.data) {
      return generatedImagePart.inlineData.data;
    }
    
    throw new Error('No image was generated by Gemini');
  } catch (error) {
    console.error('Gemini API error:', error);
    throw new Error(`Failed to process image: ${error.message}`);
  }
}

export async function onRequestPost(context) {
  try {
    const { request, env } = context;
    
    // Initialize Gemini client with environment variables
    if (!genAI) {
      const apiKey = env.GEMINI_API_KEY;
      if (!apiKey) {
        return new Response(JSON.stringify({
          error: 'GEMINI_API_KEY environment variable is not set'
        }), { 
          status: 500,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*'
          }
        });
      }
      genAI = new GoogleGenerativeAI(apiKey);
    }
    const formData = await request.formData();
    const file = formData.get('image');

    if (!file) {
      return new Response(JSON.stringify({
        error: 'No image file provided'
      }), { 
        status: 400,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        }
      });
    }

    // Validate file type
    if (!file.type.startsWith('image/')) {
      return new Response(JSON.stringify({
        error: 'File must be an image'
      }), { 
        status: 400,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        }
      });
    }

    // Validate file size (10MB limit)
    if (file.size > 10 * 1024 * 1024) {
      return new Response(JSON.stringify({
        error: 'File size must be less than 10MB'
      }), { 
        status: 400,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        }
      });
    }

    // Process the image with Gemini
    const resultBase64 = await generateGTAStyleImage(file);

    return new Response(JSON.stringify({
      success: true,
      imageBase64: resultBase64,
      originalFileName: file.name,
      processedAt: new Date().toISOString(),
    }), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      }
    });

  } catch (error) {
    console.error('Transform API error:', error);
    
    return new Response(JSON.stringify({
      error: error instanceof Error ? error.message : 'Internal server error',
      success: false
    }), {
      status: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      }
    });
  }
}

export async function onRequestGet(context) {
  return new Response(JSON.stringify({
    message: 'GTA AI Transform API',
    status: 'active',
    supportedFormats: ['image/jpeg', 'image/png', 'image/webp'],
    maxFileSize: '10MB'
  }), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*'
    }
  });
}

export async function onRequestOptions(context) {
  return new Response(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
  });
}